[project]
name = "pyrmm"
version = "0.1.5"
description = "Magisk/Apatch/Kernelsu模块的工具集"
readme = "README.MD"
authors = [
    { name = "LIghtJUNction", email = "LIghtJUNction.me@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "click>=8.2.1",
    "pydantic>=2.11.5",
    "pygithub>=2.6.1",
    "toml>=0.10.2",
]

[project.scripts]
rmm = "pyrmm.cli:cli"

[project.optional-dependencies]
ai = [
    "mcp>=1.9.3",
    "openai>=1.84.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"