name: initial

on:
  workflow_dispatch:
    inputs:
      id:
        description: '请输入模块id，例如Zygisk_shamiko'
        required: true
      
      name:
        description: '请输入模块名，例如shamiko'
        required: true

      author:
        description: '作者名'
        required: true

      description:
        description: '模块描述'
        required: true


jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.0
        with:  
          ref: main  

      - name: init__module.prop
        run: |
          echo "" > MyModule/module.prop


      - name: Get Version
        id: get_version
        run: |
          echo "date=$(date +%Y%m%d)" >> "$GITHUB_ENV"
      - name: 获取仓库 URL
        id: get_repo_url
        run: |
          echo "repo_url=https://github.com/${{ github.repository }}" >> "$GITHUB_ENV"

      - name: Add the id key in the file
        run: |
          echo "id=${{ github.event.inputs.id }}" >> MyModule/module.prop
          echo "id=${{ github.event.inputs.id }}" >> $GITHUB_ENV
      - name: Add the name key in the file
        run: |
          echo "name=${{ github.event.inputs.name }}" >> MyModule/module.prop
          echo "name=${{ github.event.inputs.name }}" >> $GITHUB_ENV
      - name: Add the version key in the file
        run: |
          echo "version=0.0.0" >> MyModule/module.prop
          echo "version=0.0.0" >> $GITHUB_ENV
      - name: Add the version code key in the file
        run: |
          echo "versionCode=${{ env.date }}" >> MyModule/module.prop
          echo "versionCode=${{ env.date }}" >> $GITHUB_ENV
      - name: Add the author key in the file
        run: |
          echo "author=${{ github.event.inputs.author }}" >> MyModule/module.prop
          echo "author=${{ github.event.inputs.author }}" >> $GITHUB_ENV
      - name: Add the description key in the file
        run: |
          echo "description=${{ github.event.inputs.description }}" >> MyModule/module.prop
          echo "description=${{ github.event.inputs.description }}" >> $GITHUB_ENV

      - name: List files for debug
        run: ls -la

      - name: init__update.json
        run: |
          echo "" > update.json
          cat <<EOF > update.json
          {
            "version": "${{ env.version }}",
            "versionCode": "${{ env.date }}",
            "zipUrl": "${{ env.repo_url }}/releases/download/${{ env.version }}/${{ env.name }}-${{ env.version }}-${{ env.versionCode }}-by${{ env.author }}.zip",
            "changelog": "${{ env.repo_url }}/raw/main/CHANGELOG.md"
          }
          EOF

      - name: init__CHANGELOG.md
        run: |
          echo "" > CHANGELOG.md
          echo -e "# Changelog 0.0.0\n\n1. 恭喜你成功创建了一个 KernelSU/Aptch/Magisk 模块项目\n2. 这是一个示例\n" >> CHANGELOG.md



      - name: Debugging Output
        run: |
          git status
          git log -1


      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "init初始化"
          git push origin main

      - name: Package module
        run: |
          # 打包模块
          zip -r "${{ env.name }}-${{ env.version }}-${{ env.versionCode }}-by${{ env.author }}.zip" *

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.version }}
          name: "${{ env.name }}-${{ env.version }}-${{ env.versionCode }}-by${{ env.author }}模块现已发布"
          body_path: CHANGELOG.md
          files: |
            ${{ env.name }}-${{ env.version }}-${{ env.versionCode }}-by${{ env.author }}.zip
          generate_release_notes: true
          fail_on_unmatched_files: false  # 如果文件匹配失败不会导致工作流失败
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
